// Generated by the beam-codegen .  DO NOT EDIT!
package com.yzl.framework.beam.proto;

import com.yzl.framework.beam.annotation.BeamInterface;

@BeamInterface
public interface Simple{
   Helloworld.HelloReply sayHello(Helloworld.HelloRequest helloRequest);
}
